apiVersion : apps/v1
kind: Deployment
metadata:
  name: apicontagemaula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicontagemaula
  template:
    metadata:
      labels:
        app: apicontagemaula
    spec:
      containers:
        - name: apicontagemaula
          image: groffeazuredevops.azurecr.io/apicontagem
          env:
            - name: MensagemVariavel
              value: Utilizando o Azure Kubernetes Service (AKS)
          ports:
          - containerPort: 80
