apiVersion : apps/v1
kind: Deployment
metadata:
  name: apicounter
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apicounter
  template:
    metadata:
      labels:
        app: apicounter
    spec:
      containers:
        - name: apicounter
          image: trainingazuredevopsacr01.azurecr.io/apicounter:latest
          env:
            - name: MensagemVariavel
              value: Utilizando o Azure Kubernetes Service (AKS) - Escalado para 5 Pods
          ports:
          - containerPort: 80
